#to open a program called spider.txt
file = open("spider.txt")
#creates a new file object and assigns it a variable called "file"

#the parameter passed to open() is the name of the fiel we want to open - we are assuming it's in the same directory we're working in

#when we open the file, the OS checks that we have permission to open the file and then gives the code a file descriptor

#file descriptor - token, generated by the OS, that allows programs to do more operations with the file

#descriptor is stored as an attribute of the file's object

#file object gives us a bunch of methods that we can use to operate with the file.

print(file.readline())

#readline() lets us read a single line of a file

#if you call it again it will read the next line, and so on

print(file.read())
#reads from current position to end of file

file.close()
#closes the file when you are done

#when a file is open, it is locked by OS
#limited number of file descriptors can be created at once
#leaving open files can lead to race conditions

with open("/home/drtaylor1701/Documents/Using Python to interact with the operating system/Reading_and_writing_files/spider.txt") as file:
    print(file.readline())

#lets us create a block of code to use with a file and then closes the file when the code block is done
#Sometimes this is not ideal if your code is really long or something